# Generated by Django 5.0.6 on 2026-06-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_skill_employeeskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('on_leave', 'On Leave'), ('away', 'Away')], db_index=True, default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(choices=[('office', 'Office'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_index=True, default='office', max_length=20),
        ),
    ]
