# Generated by Django 5.0.6 on 2026-06-19 07:42

import django.core.validators
import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_availability_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resume', 'Resume/CV'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('government_id', 'Government ID'), ('training', 'Training Record'), ('performance', 'Performance Document'), ('other', 'Other')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=employees.models.employee_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('excellence', 'Excellence'), ('teamwork', 'Teamwork'), ('innovation', 'Innovation'), ('leadership', 'Leadership'), ('milestone', 'Milestone'), ('other', 'Other')], default='excellence', max_length=20)),
                ('awarded_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognitions_given', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='employees.employee')),
            ],
            options={
                'ordering': ['-awarded_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('hire', 'Hired'), ('promotion', 'Promotion'), ('transfer', 'Transfer'), ('award', 'Award'), ('certification', 'Certification'), ('review', 'Performance Review'), ('other', 'Other')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='employees.employee')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
