# Generated by Django 5.0.6 on 2026-06-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_github_url_employee_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('probationary', 'Probationary'), ('contractual', 'Contractual'), ('intern', 'Intern')], db_index=True, default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
