# Generated by Django 5.0.6 on 2026-06-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Require password change on next login.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Administrator'), ('hr_manager', 'HR Manager'), ('employee', 'Employee')], db_index=True, default='employee', max_length=20),
        ),
    ]
