# Generated by Django 5.0.6 on 2026-07-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hr_manager', 'HR Manager'), ('employee', 'Employee')], db_index=True, default='employee', max_length=20),
        ),
    ]
