# Generated by Django 5.0.6 on 2026-06-29 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('company_event', 'Company Event')], db_index=True, default='holiday', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calendar entry',
                'verbose_name_plural': 'calendar entries',
                'ordering': ['date', 'title'],
                'indexes': [models.Index(fields=['date', 'event_type'], name='company_cal_date_0015a4_idx'), models.Index(fields=['is_active', 'date'], name='company_cal_is_acti_8f8855_idx')],
            },
        ),
    ]
