# Generated by Django 5.0.6 on 2026-06-19 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active', 'name'], name='departments_is_acti_de4276_idx'),
        ),
    ]
